### ISSUE TITLE
爬取失败

### ISSUE THREAD

**Issue by sunpeishuai** [derek-s/Python-Tianyancha#2]
我这边用的python3.6(32) + geckodriver-v0.19.1-win64 + firefox 58.0.1(64) 但是总是失败，能否告知一下问题出在哪  或者给一个成熟的环境

**Comment by derek-s** [comment]
不清楚你那边遇到的是什么问题，而且这个项目是我自己练手用的。
你也没有描述失败情况，比如有什么报错。

**Comment by sunpeishuai** [comment]
F:\Python-Tianyancha>python main.py
https://static.tianyancha.com/m-require-js/public/styles/main-3d97b30e9c.css
download font
tyc-num-9d312ff8af.ttf
Traceback (most recent call last):
  File "main.py", line 370, in <module>
    main(logfile, excel)
  File "main.py", line 319, in main
    maping, fontname = gettycfont()
  File "main.py", line 232, in gettycfont
    return getmaping(recode[0]), recode[0]
  File "main.py", line 284, in getmaping
    numlist = tuple(pytesseract.image_to_string(fontimage))
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by twtytei** [comment]
@derek-s 首先谢谢你的分享，可能大多数人都只是一个编程爱好者，并不像你们技术那么好，所以还望多指点一些。下附错误提示：
D:\Anaconda3\python.exe G:/Python-Tianyancha-master/main3.py
https://static.tianyancha.com/m-require-js/public/styles/main-3d97b30e9c.css
download font
tyc-num-9d312ff8af.ttf
Traceback (most recent call last):
  File "G:/Python-Tianyancha-master/main3.py", line 411, in <module>
    main(logfile, excel)
  File "G:/Python-Tianyancha-master/main3.py", line 360, in main
    maping, fontname = gettycfont()
  File "G:/Python-Tianyancha-master/main3.py", line 273, in gettycfont
    return getmaping(recode[0]), recode[0]
  File "G:/Python-Tianyancha-master/main3.py", line 325, in getmaping
    numlist = tuple(pytesseract.image_to_string(fontimage))
  File "D:\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "D:\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "D:\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Process finished with exit code 1

**Comment by sunpeishuai** [comment]
我开始用的python3出现error 又改用的python2还是error。问题应该都是出在同一个地方。
因为我并不是python开发人员，只是因为一些事情需要临时爬一些数据，有些问题不能明了的告知与你。还望海涵。

**Comment by derek-s** [comment]
@sunpeishuai @twtytei 
两位遇到的是同样的问题，系统内缺少tesseract的程序，因为源码中有用到图像识别这一块的东西。
两位可以搜索一下Windows上如何安装tesseract-ocr
安装好之后再尝试一下看看。

**Comment by sunpeishuai** [comment]
@derek-s @twtytei 谢谢 我这边搞定了
安装tesseract后设置环境变量path TESSDATA_PREFIX为安装路径 并重启PC 就可以了

**Comment by twtytei** [comment]
@all谢谢分享，谢谢指点
