### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by elegentcode** [derek-s/Python-Tianyancha#9]
很荣幸查看你的优秀代码，但是我在尝试运行时出现了错误，如下：
win10 Python3.6，已经安装并配置好tesseract、依赖环境，运行时出现如下错误
---------------------------------------------------------------------------
Message: 'geckodriver.exe' executable needs to be in PATH. 

https://static.tianyancha.com/fonts-styles/css/63/63cca7cc/font.css
download font
https://static.tianyancha.com/fonts-styles/fonts/63/63cca7cc/tyc-num.ttf
处理数字加密映射
0
Traceback (most recent call last):
  File "G:\python\QueryTyc\Python-Tianyancha-master\main3.py", line 484, in <module>
    main(logfile, excel)
  File "G:\python\QueryTyc\Python-Tianyancha-master\main3.py", line 433, in main
    maping, fontname = gettycfont()
  File "G:\python\QueryTyc\Python-Tianyancha-master\main3.py", line 307, in gettycfont
    return getmaping("tyc-num.ttf"), fontpath_name[0]
  File "G:\python\QueryTyc\Python-Tianyancha-master\main3.py", line 367, in getmaping
    num = pytesseract.image_to_string(fontimage, config="-psm 6")
  File "c:\python36\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "c:\python36\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "c:\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
---------------------------------------------------------------------
如有时间希望查看一下，感谢！

**Comment by derek-s** [comment]
报错信息已经说明是你pytesseract无法启动tesseract-ocr
检查一下你tesseract-ocr的安装和配置吧。

**Comment by elegentcode** [comment]
感谢，问题已经解决，有些信息识别的不准确。

**Comment by derek-s** [comment]
@elegentcode 早期天眼查只是将数字进行了替换，现在中文也开始替换了，目前使用的是OCR中文识别，限于OCR识别的问题，所以信息识别会受到OCR识别的正确率的影响的。
